### ISSUE TITLE
Misc tasks towards large-scale linear and nonlinear problems with GridapDistributed + GridapPETSc

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapPETSc.jl#52]
## High-priority
- [ ] Refactor  `PetscNonlinearSolver`. Issue: #45  
- [ ] Fix `copy!`. Issue #50 
- [ ] Refactor mpi tests with a TestApp and try to put as much drivers as possible in the same mpi run to reuse JIT compilation cache. Essentially, all test requiring the same number of procs can be in the same run. This should reduce the CI time significantly
- [ ] Garbage collection of petsc objects. Issue #41. To fully fix this, it is likely that  we need to fix #51 first.

It would be nice to have all functionality working in native sequential (just as before), as well as in distributed sequential and distributed mpi mode.

**Comment by fverdugo** [comment]
@amartinhuertas feel free to add more tasks and comments here

**Comment by amartinhuertas** [comment]
I added the tasks in issue #45
